name: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules'
        key: npm-v3-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --no-audit --prefer-offline
      shell: bash
      env:
        SKIP_COMPILE: true

    - name: Install Truffle
      run: npm install -g --no-audit --prefer-offline truffle
      shell: bash
