name: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: npm

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: npm-v3-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci --prefer-offline
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        SKIP_COMPILE: true

    - name: Cache Global node modules
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: npm-v3-${{ hashFiles('**/package-lock.json') }}

    - name: Install Truffle
      run: npm install truffle -g
      shell: bash
