# Reference: https://github.com/marketplace/actions/setup-node-js-environment

name: Truffle Test

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Show NodeJS version
      run: npm --version

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Truffle
      run: npm install truffle -g

    - name: Install Truffle Dependencies
      run: npm ci

    - name: Run Truffle Test
      run: npm run test
